CHD_Wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Wiki.urls')),
    path("admin/", admin.site.urls),
]

Wiki/urls.py
from django.urls import path
from .views import user, blog, schedule, group


app_name = 'helper'
urlpatterns = [
    path('register/', user.register, name='register'),
    path('login/', user.login, name='login'),
    path('zy/', user.zy, name='zy'),
    path('kc/', user.kc, name='kc'),
    path('gy/', user.gy, name='gy'),
    path('', user.index, name='index'),
    path('user/home/', user.home, name='home'),
    path('user/pwd_change/', user.pwd_change, name='pwd_change'),
    path('user/friends_admin/', user.friends_admin, name='friends_admin'),
    path('blog/home/', blog.home, name='blog_homepage'),
    path('blog/hot/<int:pg>', blog.hot, name='hot'),
    path('blog/<int:pk>/modify', blog.modify, name='blog_modify'),
    path('blog/<int:pk>/delete', blog.delete, name='blog_delete'),
    path('blog/add', blog.add, name='blog_add'),
    path('blog/<int:pk>/', blog.blog, name='blog_page'),
    path('blog/friend/<int:friend_id>/', blog.public, name='public'),
    path('logout/', user.logout, name='logout'),
    path('group/', group.group_admin, name='group_admin'),
    path('group/<int:pk>/', group.home, name='group_home'),
    path('group/<int:pk>/add_assign/', group.add_assign, name='assign_add'),
    path('group/<int:pk>/add_sub_assign/', group.add_sub_assign, name='sub_assign_add'),
    path('schedule/', schedule.home, name='schedule_home'),
    path('schedule/add/', schedule.add_todo_list, name='schedule_add'),
    path('schedule/daily', schedule.daily_schedules, name='schedule_daily'),
]

Wiki/views/schedule.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.forms import Form
from django.forms import fields
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from Wiki import models
import datetime
import copy
from .settings import *


class TodoForm(Form):
    CYCLE_CHOICES = (
        ('N', '不重复'),
        ('D', '每天'),
        ('W', '每周'),
        ('M', '每月')
    )
    REPEAT_CYCLE = (
        (False, '不重复'),
        (True, '重复')
    )
    description = fields.CharField(label='日程描述', required=True, max_length=50,
                                   widget=forms.TextInput(attrs={
                                       'class': 'form-control form-control-user mb-5'
                                   }))
    type = fields.CharField(label='日程类型', required=True, max_length=2,
                            widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    weight = fields.IntegerField(label='权重', required=True, max_value=100,
                                 widget=forms.NumberInput(attrs={'class': 'form-control form-control-user mb-5'}))
    is_repeated = fields.ChoiceField(label='是否重复', choices=REPEAT_CYCLE, widget=forms.RadioSelect)
    repeat_cycle = fields.ChoiceField(label='重复周期', required=False, choices=CYCLE_CHOICES, widget=forms.RadioSelect)
    start_time = fields.DateTimeField(label='开始时间', required=True,
                                      widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    deadline = fields.DateTimeField(label='截止时间', required=True,
                                    widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    expected_minutes_consumed = fields.IntegerField(label='预期花费时间', required=False,
                                                    widget=forms.NumberInput(
                                                        attrs={'class': 'form-control form-control-user mb-5'}))


@login_required
def add_todo_list(request):
    if request.method == "GET":
        form = TodoForm()
        return render(request, "../templates/schedule/add_schedule.html", {'form': form})
    else:
        form = TodoForm(request.POST)
        if form.is_valid():
            user = request.user
            description = form.cleaned_data['description']
            type = form.cleaned_data['type']
            is_repeated = form.cleaned_data['is_repeated']
            repeat_cycle = form.cleaned_data['repeat_cycle']
            if repeat_cycle == 'N':
                repeat_cycle = None
            start_time = form.cleaned_data['start_time']
            weight = form.cleaned_data['weight']
            deadline = form.cleaned_data['deadline']
            emc = form.cleaned_data['expected_minutes_consumed']
            models.Schedule.objects.create(user_id=user.id, description=description, type=type, is_repeated=is_repeated,
                                           is_done=False, start_time=start_time, weight=weight, deadline=deadline,
                                           expected_minutes_consumed=emc, repeat_cycle=repeat_cycle)
            return HttpResponseRedirect(reverse("helper:schedule_home"))
        else:
            message = "添加失败！"
            return render(request, "../templates/schedule/add_schedule.html", {'form': form, 'message': message})


def get_schedules(user, search_day_num):
    schedule_not_repeated = user.schedule_set.filter(is_done__exact=False, is_repeated__exact=False)
    schedule_daily = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='D',
                                              deadline__gte=timezone.now())
    schedule_weekly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='W',
                                               deadline__gte=timezone.now())
    schedule_monthly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='M',
                                                deadline__gte=timezone.now())

    def update_time(s, i, schedules):
        time = datetime.datetime.now() + datetime.timedelta(days=i)
        if i == 0:
            finish_time_range = (
                datetime.datetime.combine(datetime.date.today(), datetime.datetime.min.time()),
                datetime.datetime.combine(datetime.date.today(), datetime.datetime.max.time())
            )
            if len(models.FinishedSchedule.objects.filter(finish_time__range=finish_time_range, schedule_id=s.id)) != 0:
                return

        interval = time.date() - s.start_time.date()
        s.start_time += datetime.timedelta(days=interval.days)
        if s.start_time <= s.deadline:
            schedules.append(s)

    schedules = list(schedule_not_repeated)
    for i in range(search_day_num):
        time = datetime.datetime.now() + datetime.timedelta(days=i)
        for j in range(len(schedule_daily)):
            s = copy.copy(schedule_daily[j])
            update_time(s, i, schedules)
        for j in range(len(schedule_weekly)):
            s = copy.copy(schedule_weekly[j])
            if s.start_time.weekday() == time.weekday():
                update_time(s, i, schedules)
        for j in range(len(schedule_monthly)):
            s = copy.copy(schedule_monthly[j])
            if s.start_time.day == time.day:
                update_time(s, i, schedules)
    schedules.sort(key=lambda sc: sc.start_time)
    return schedules


@login_required
def home(request):
    user = request.user
    search_day_num = HOMEPAGE_SCHEDULE_DAY
    if request.method == 'POST':
        day_num = request.POST.get('search_day_num')
        finish_id = request.POST.get('finish_id')
        time_consumed = request.POST.get('time_consumed')
        if not (day_num is None):
            search_day_num = int(day_num)
        if not (finish_id is None):
            schedule = models.Schedule.objects.filter(id=finish_id)[0]
            if not schedule.is_repeated:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
                schedule.is_done = True
                schedule.save()
            elif not (time_consumed is None):
                if time_consumed != "":
                    models.FinishedSchedule.objects.create(schedule_id=finish_id, minutes_consumed=time_consumed)
                else:
                    models.FinishedSchedule.objects.create(schedule_id=finish_id)
            else:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)

    schedules = get_schedules(user, search_day_num)
    daily_schedules = get_schedules(user, 1)
    for ds in daily_schedules:
        if ds.is_repeated == True:
            ds.deadline = ds.start_time + datetime.timedelta(minutes=ds.expected_minutes_consumed)
    return render(request, "../templates/schedule/home.html",
                  {
                      'schedules': schedules,
                      'day_num': search_day_num,
                      'daily_schedules': daily_schedules
                  })


@login_required
def daily_schedules(request):
    user = request.user
    if request.method == 'POST':
        finish_id = request.POST.get('finish_id')
        time_consumed = request.POST.get('time_consumed')
        if not (finish_id is None):
            schedule = models.Schedule.objects.filter(id=finish_id)[0]
            if not schedule.is_repeated:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
                schedule.is_done = True
                schedule.save()
            elif not (time_consumed is None):
                models.FinishedSchedule.objects.create(schedule_id=finish_id, minutes_consumed=time_consumed)
            else:
                models.FinishedSchedule.objects.create(schedule_id=finish_id)
    schedules = get_schedules(user, 1)
    for s in schedules:
        if s.is_repeated:
            s.deadline = s.start_time + datetime.timedelta(minutes=s.expected_minutes_consumed)
    return render(request, "../templates/schedule/daily_schedules.html", {'schedules': schedules})

templates/schedule/add_schedule.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

        <title>Adding Schedule</title>

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
{% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body class="bg-gradient-primary">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white  mb-4 static-top shadow-lg">
                    <a href="{% url 'helper:home' %}">CHD Wiki</a>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                <!-- Nav Item - User Information -->
                <li class="nav-item">
                    <a class="nav-link" id="userName">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userId">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userEmail">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:home' %}">
                        <span class="mr-2 d-none d-lg-inline text-primary small">返回主页</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="loginOut" role="button" href="#" onclick="window.close();">
                        <span class="mr-2 d-none d-lg-inline text-danger small">关闭页面</span>
                    </a>
                </li>
            </ul>
        </nav></div>

            <!-- Content Column -->
            <div class="col-xl-8 col-lg-12 col-md-12 m-auto">

                <!-- Schedule -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3 ">
                        <h6 class="m-0 font-weight-bold text-primary text-center">添加日程</h6>
                    </div>
                    <div class="card-body">
                       <form method="post">
                           {% csrf_token %}
                           {{ form }}
                           <input type="submit" class="btn btn-primary btn-block" value="提交">
                           {% if message %}
                            <script>
                                mes = "{{message}}";
                                if (!mes.match("message"))
                                    alert(mes);
                            </script>
                            {% endif %}
                       </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

</body>

templates/schedule/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Schedule Home</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-icon">
                    <img src="../../static/img/logo.png" class="fas fa-laugh-wink" width="50" height="50"></img>
                </div>
                <div class="sidebar-brand-text mx-3">CHD Wiki</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                博客
            </div>

            <!-- Nav Item - My Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门博客</span>
                </a>
            </li>

            <!-- Nav Item -  Hot Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:blog_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的博客</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                小组
            </div>
            <!-- Nav Item - Group Task Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:group_admin' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>小组任务</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>CHD Wiki</strong> 助力每一个CHDer</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item">
                            <a class="nav-link" id="userName">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userId">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userEmail">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                            </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">日程管理</h1>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-8 mb-4">

                            <!-- My Groups -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">我的日程</h6>
                                </div>
                                <div class="card-body">
                                    <p>查询天数：</p>
                                    <form method="post">
                                        {% csrf_token %}
                                        <label>
                                            <input type="number" name="search_day_num" value="{{ day_num }}">
                                        </label>
                                        <button class="btn btn-primary" name="search">查询</button>
                                    </form>
                                    <ul>
                                        {% if schedules %}
                                            {% for s in schedules %}
                                                <li>{{ s.description }} {{ s.start_time }}</li>
                                                <form method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="finish_id" value="{{ s.id }}">
                                                    {% if False %}
                                                        <input type="number" name="time_consumed" placeholder="花费时间">
                                                        <button class="btn btn-primary" name="agree">完成</button>
                                                    {% endif %}
                                                </form>
                                             {% endfor %}
                                        {% endif %}
                                    </ul>
                                    <a target="_blank" href="{% url 'helper:schedule_add' %}">新建日程</a>
                                </div>
                            </div>

                        </div>

                        <div class="col-lg-4 mb-4">

                            <!-- Groups List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">今日日程</h6>
                                </div>
                                <div class="card-body">
                                    <p style="text-align: center">
                                        <a target="_blank" href="{% url 'helper:schedule_add' %}">新建日程</a></p>
                                    <ul>
                                        {% if daily_schedules %}
                                            {% for s in daily_schedules %}
                                                <li>{{ s.description }}
                                                    {% if s.is_repeated %}
                                                        {{ s.start_time }} ~ {{ s.deadline }}
                                                    {% else %}
                                                        截止日期：{{ s.deadline }}
                                                    {% endif %}
                                                </li>
                                                <form method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="finish_id" value="{{ s.id }}">
                                                    {% if True %}
                                                        <input type="number" name="time_consumed" placeholder="花费时间">
                                                    {% endif %}
                                                    <button class="btn btn-primary" name="agree">完成</button>
                                                </form>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>