CHD_Wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Wiki.urls')),
    path("admin/", admin.site.urls),
]

Wiki/urls.py
from django.urls import path
from .views import user, blog, schedule, group


app_name = 'helper'
urlpatterns = [
    path('register/', user.register, name='register'),
    path('login/', user.login, name='login'),
    path('zy/', user.zy, name='zy'),
    path('kc/', user.kc, name='kc'),
    path('gy/', user.gy, name='gy'),
    path('', user.index, name='index'),
    path('user/home/', user.home, name='home'),
    path('user/pwd_change/', user.pwd_change, name='pwd_change'),
    path('user/friends_admin/', user.friends_admin, name='friends_admin'),
    path('blog/home/', blog.home, name='blog_homepage'),
    path('blog/hot/<int:pg>', blog.hot, name='hot'),
    path('blog/<int:pk>/modify', blog.modify, name='blog_modify'),
    path('blog/<int:pk>/delete', blog.delete, name='blog_delete'),
    path('blog/add', blog.add, name='blog_add'),
    path('blog/<int:pk>/', blog.blog, name='blog_page'),
    path('blog/friend/<int:friend_id>/', blog.public, name='public'),
    path('logout/', user.logout, name='logout'),
    path('group/', group.group_admin, name='group_admin'),
    path('group/<int:pk>/', group.home, name='group_home'),
    path('group/<int:pk>/add_assign/', group.add_assign, name='assign_add'),
    path('group/<int:pk>/add_sub_assign/', group.add_sub_assign, name='sub_assign_add'),
    path('schedule/', schedule.home, name='schedule_home'),
    path('schedule/add/', schedule.add_todo_list, name='schedule_add'),
    path('schedule/daily', schedule.daily_schedules, name='schedule_daily'),
]

Wiki/views/blog.py
from django import forms
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponseForbidden, HttpResponseNotFound
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from ..models import *
from .settings import *
import datetime
import math


class ModifyForm(forms.Form):
    title = forms.CharField(label='标题', max_length=50,
                            widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    content = forms.CharField(label='博客内容', widget=forms.Textarea(attrs={'class': 'form-control form-control-user mb-5'}))


@login_required
def home(request):
    user = request.user

    blogs = Blog.objects.filter(user_id__exact=user.id).order_by('-modified_time')
    collections = Collection.objects.filter(user_id__exact=user.id).order_by('-blog__collect_amount')
    return render(request, '../templates/blog/home.html',
                  {
                      'blogs': blogs,
                      'collections': collections
                  })


@login_required
def blog(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    user: User = request.user
    if user.collection_set.filter(blog_id__exact=blog.pk).count() == 0:
        is_collected = False
    else:
        is_collected = True
    comments = blog.comment_set.all().order_by('created_time')
    if request.method == 'POST':
        delete_comment = request.POST.get('delete_comment')
        create_comment = request.POST.get('create_comment')
        collect_blog = request.POST.get('collect_blog')
        if not (delete_comment is None):
            try:
                comment = Comment.objects.filter(user_id__exact=user.id,
                                                 blog_id__exact=blog.id,
                                                 content__exact=delete_comment)[0]
                comment.delete()
            except IndexError:
                pass

        if not (collect_blog is None):
            collection = Collection.objects.filter(user_id__exact=user.id, blog_id__exact=blog.id)
            if len(collection) == 0:
                new_collection = Collection(user=user, blog=blog)
                blog.collect_amount += 1
                blog.save()
                new_collection.save()
                is_collected = True
            else:
                collection.delete()
                is_collected = False

        if not (create_comment is None):
            new_comment = Comment(user=user, blog=blog, content=create_comment)
            new_comment.save()
    else:
        blog.pageview += 1
        blog.save()

    return render(request, '../templates/blog/blog.html',
                  {'blog': blog, 'comments': comments, 'user': user, 'is_collected': is_collected})


@login_required
def modify(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if blog.user != request.user:
        return HttpResponseForbidden

    if request.method == "POST":
        form = ModifyForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            blog.title = title
            blog.content = content
            blog.save()
            return HttpResponseRedirect(reverse('helper:blog_page', args=(blog.id,)))
    else:
        form = ModifyForm(initial={'title': blog.title, 'content': blog.content})

    return render(request, '../templates/blog/modify.html', {'form': form})


@login_required
def delete(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    if blog.user != request.user:
        return HttpResponseForbidden
    blog.delete()
    return HttpResponseRedirect(reverse("helper:blog_homepage"))


@login_required
def add(request):
    user = request.user

    if request.method == "POST":
        form = ModifyForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            content = form.cleaned_data['content']
            blog = Blog(user=user, title=title, content=content)
            blog.save()
            return HttpResponseRedirect(reverse('helper:blog_page', args=(blog.id,)))
    else:
        form = ModifyForm()

    return render(request, '../templates/blog/modify.html', {'form': form})


def hot(request, pg):
    blogs = Blog.objects.filter(Q(user__blog__pageview__gte=HOT_BLOG_PAGEVIEW,
                                  modified_time__gte = timezone.now() -
                                                       datetime.timedelta(days=BLOGPAGE_HOT_BLOG_DAY)) |
                                Q(modified_time__gte = timezone.now() -
                                                       datetime.timedelta(days=BLOGPAGE_COMMON_BLOG_DAY))).distinct().order_by('-modified_time')
    page_num = math.ceil(len(blogs) / BLOGPAGE_BLOG_NUMBER)
    if pg > page_num or pg < 1:
        return HttpResponseNotFound()

    if pg * BLOGPAGE_BLOG_NUMBER > len(blogs):
        number = len(blogs)
    else:
        number = pg * BLOGPAGE_BLOG_NUMBER

    blogs = blogs[(pg - 1) * BLOGPAGE_BLOG_NUMBER: number]
    return render(request, '../templates/blog/hot.html',
                  {
                      'blogs': blogs,
                      'page_num': page_num,
                      'current_page': pg
                  })


@login_required
def public(request, friend_id):
    user: User = request.user
    friend = Friend.objects.filter(user_id__exact=user.id, friend_id__exact=friend_id)
    if len(friend) == 0 and friend_id != user.id:
        return HttpResponseForbidden()
    blogs = Blog.objects.filter(user_id__exact=friend_id)
    message = None
    if friend_id == user.id:
        friend_user = user
    else:
        friend_user = friend[0].friend
        if friend[0].authority == 0:
            blogs = None
            message = "没有权限访问！"

    return render(request, '../templates/blog/friend.html',
                  {
                      'blogs': blogs,
                      'friend': friend_user,
                      'message': message
                  })

templates/blog/friend.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Friend</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-icon">
                    <img src="{% static 'img/logo.png' %}" class="fas fa-laugh-wink" width="50" height="50"></img>
                </div>
                <div class="sidebar-brand-text mx-3">CHD Wiki</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                博客
            </div>

            <!-- Nav Item - My Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门博客</span>
                </a>
            </li>

            <!-- Nav Item -  Hot Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:blog_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的博客</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                小组
            </div>
            <!-- Nav Item - Group Task Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:group_admin' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>小组任务</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>CHD Wiki</strong> 助力每一个CHDer</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                    <li class="nav-item">
                        <a class="nav-link" id="userName">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" id="userId">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="userEmail">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                        </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">好友主页</h1>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-9 mb-4">

                            <!-- Friend's Recent Blogs -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">近期博文</h6>
                                </div>
                                <div class="card-body">
                                    {% if blogs %}
                                        {% for b in blogs %}
                                            <h4><a target="_blank" href="{% url 'helper:blog_page' b.id %}">{{ b.title }}</a></h4>
                                            <p>{{ b.created_time }} 热度:{{ b.pageview }}</p>
                                            <p>{{ b.content|truncatechars:200 }}</p>
                                            <hr class="divider">
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </div>

                        </div>

                        <div class="col-lg-3 mb-4">

                            <!-- Friend Info -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">好友资料</h6>
                                </div>
                                <div class="card-body">
                                    <ul>
                                        <li>{{ friend.username }}</li>
                                        <li>{{ friend.email }}</li>
                                        <li>{{ friend.profile.name }}</li>
                                    </ul>
                                </div>
                            </div>

                            <!-- Friend’s Blog List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">博客列表</h6>
                                </div>
                                <div class="card-body">
                                    {% if blogs %}
                                    {% for b in blogs %}
                                    <p><a target="_blank" href="{% url 'helper:blog_page' b.id %}">{{ b.title }}</a></p>
                                    {% endfor %}
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/blog/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-icon">
                    <img src="../../static/img/logo.png" class="fas fa-laugh-wink" width="50" height="50" alt="logo"/>
                </div>
                <div class="sidebar-brand-text mx-3">CHD Wiki</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                博客
            </div>

            <!-- Nav Item - My Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门博客</span>
                </a>
            </li>

            <!-- Nav Item -  Hot Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:blog_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的博客</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                小组
            </div>
            <!-- Nav Item - Group Task Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:group_admin' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>小组任务</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>CHD Wiki</strong> 助力每一个CHDer</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                    <li class="nav-item">
                        <a class="nav-link" id="userName">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" id="userId">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="userEmail">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                        </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">我的博客</h1>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-9 mb-4">

                            <!-- Friend's Recent Blogs -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">最近发表</h6>
                                </div>
                                <div class="card-body">
                                    <article>
                                        <p style="text-align: center;"> <a target="_blank" href="{% url 'helper:blog_add' %}">新建博客</a> </p>
                                        {% if blogs %}
                                            {% for b in blogs %}
                                                <h4><a target="_blank" href="{% url 'helper:blog_page' b.id %}">{{ b.title }}</a></h4>
                                                <p>{{ b.created_time }} 热度:{{ b.pageview }}</p>
                                                <p>{{ b.content|truncatechars:200 }}</p>
                                                <hr class="divider">
                                            {% endfor %}
                                        {% endif %}
                                    </article>
                                </div>
                            </div>

                        </div>

                        <div class="col-lg-3 mb-4">

                            <!-- Friend Info -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">我的收藏</h6>
                                </div>
                                <div class="card-body">
                                    {% if collections %}
                                        <ul>
                                            {% for c in collections %}
                                                <li><a target="_blank" href="{% url 'helper:blog_page' c.blog.id %}">{{ c.blog.title }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                            </div>

                            <!-- Friend’s Blog List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">我的博客</h6>
                                </div>
                                <div class="card-body">
                                    {% if blogs %}
                                        <ul>
                                            {% for b in blogs %}
                                                <li><a target="_blank" href="{% url 'helper:blog_page' b.id %}">{{ b.title }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>