CHD_Wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Wiki.urls')),
    path("admin/", admin.site.urls),
]

Wiki/urls.py
from django.urls import path
from .views import user, blog, schedule, group


app_name = 'helper'
urlpatterns = [
    path('register/', user.register, name='register'),
    path('login/', user.login, name='login'),
    path('zy/', user.zy, name='zy'),
    path('kc/', user.kc, name='kc'),
    path('gy/', user.gy, name='gy'),
    path('', user.index, name='index'),
    path('user/home/', user.home, name='home'),
    path('user/pwd_change/', user.pwd_change, name='pwd_change'),
    path('user/friends_admin/', user.friends_admin, name='friends_admin'),
    path('blog/home/', blog.home, name='blog_homepage'),
    path('blog/hot/<int:pg>', blog.hot, name='hot'),
    path('blog/<int:pk>/modify', blog.modify, name='blog_modify'),
    path('blog/<int:pk>/delete', blog.delete, name='blog_delete'),
    path('blog/add', blog.add, name='blog_add'),
    path('blog/<int:pk>/', blog.blog, name='blog_page'),
    path('blog/friend/<int:friend_id>/', blog.public, name='public'),
    path('logout/', user.logout, name='logout'),
    path('group/', group.group_admin, name='group_admin'),
    path('group/<int:pk>/', group.home, name='group_home'),
    path('group/<int:pk>/add_assign/', group.add_assign, name='assign_add'),
    path('group/<int:pk>/add_sub_assign/', group.add_sub_assign, name='sub_assign_add'),
    path('schedule/', schedule.home, name='schedule_home'),
    path('schedule/add/', schedule.add_todo_list, name='schedule_add'),
    path('schedule/daily', schedule.daily_schedules, name='schedule_daily'),
]

Wiki/views/group.py
from django.shortcuts import render, get_object_or_404
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from Wiki import models


class SubAssignmentForm(forms.Form):
    description = forms.CharField(label='子任务描述', required=True, max_length=50,
                                  widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    pre_sub_assignment = forms.CharField(label='前置子任务', required=False, max_length=50,
                                         widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    start_time = forms.DateTimeField(label='开始时间', required=True,
                                     widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    deadline = forms.DateTimeField(label='截止日期', required=True,
                                   widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))
    user = forms.ModelChoiceField(label='用户', queryset=User.objects.all(), required=True,
                                  widget=forms.Select(attrs={'class': 'form-control form-control-user mb-5'}))
    assignment = forms.ModelChoiceField(label='父任务', queryset=models.GroupAssignment.objects.all(), required=True,
                                        widget=forms.Select(attrs={'class': 'form-control form-control-user mb-5'}))
    weight = forms.IntegerField(label='权重', required=True, max_value=100,
                                widget=forms.NumberInput(attrs={'class': 'form-control form-control-user mb-5'}))
    expected_minutes_consumed = forms.IntegerField(label='预期花费时间', required=True,
                                                   widget=forms.NumberInput(
                                                       attrs={'class': 'form-control form-control-user mb-5'}))


class GroupForm(forms.Form):
    type = forms.CharField(label='小组类型', required=True, max_length=20)
    group_name = forms.CharField(label='小组名称', required=True, max_length=20)


class AssignmentForm(forms.Form):
    description = forms.CharField(label='任务描述', required=True, max_length=1000,
                                  widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    deadline = forms.DateTimeField(label='截止日期', required=True,
                                   widget=forms.DateTimeInput(attrs={'class': 'form-control form-control-user mb-5'}))


@login_required
def group_admin(request):
    user = request.user
    leader_groups = None
    message = None
    if request.method == 'POST':
        add_group = request.POST.get('group_name')
        leader_id = request.POST.get('leader_id')
        group_id = request.POST.get('group_id')
        if not(add_group is None):
            type = request.POST.get('type')
            name = request.POST.get('group_name')
            group = models.Group(type=type, group_name=name, leader=user)
            group.save()
            models.UserGroup.objects.create(is_leader=True, group=group, user=user)

        if not(leader_id is None):
            try:
                leader = models.User.objects.filter(username=leader_id)[0]
                leader_groups = models.Group.objects.filter(leader_id__exact=leader.id)
            except IndexError:
                leader_groups = None
                message = "组长的学号不存在！"

        if not(group_id is None):
            if len(models.UserGroup.objects.filter(group_id=group_id, user_id=user.id)) == 0 and \
                    len(models.Group.objects.filter(id=group_id)) != 0:
                user_group = models.UserGroup(is_leader=False, group_id=group_id, user=user)
                user_group.save()
            else:
                message = "请输入正确的组号！"

    add_form = GroupForm()
    user_groups = models.UserGroup.objects.filter(user_id=user.id)
    groups = list(map(lambda k: k.group, user_groups))

    return render(request, '../templates/group/groups_admin.html',
                  {
                      'add_form': add_form,
                      'groups': groups,
                      'leader_groups': leader_groups,
                      'message': message
                  })


@login_required
def add_sub_assign(request, pk):
    user = request.user
    group = get_object_or_404(models.Group, pk=pk)
    if user.id != group.leader.id:
        return HttpResponseForbidden
    if request.method == "GET":
        form = SubAssignmentForm()
        qs_user = User.objects.filter(usergroup__group_id=group.id)
        qs_assign = models.GroupAssignment.objects.filter(group_id=group.id).distinct()
        form.fields['user'].queryset = qs_user
        form.fields['assignment'].queryset = qs_assign
        return render(request, "../templates/group/add_sub_assign.html", {'form': form})
    else:
        form = SubAssignmentForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['user']
            user = User.objects.filter(username=username)[0]
            assignment_id = models.GroupAssignment.objects.filter(group=group,
                                                                  description=form.cleaned_data['assignment'])[0].id
            description = form.cleaned_data['description']
            deadline = form.cleaned_data['deadline']
            weight = form.cleaned_data['weight']
            pre_sub_assignment = form.cleaned_data['pre_sub_assignment']
            emc = form.cleaned_data['expected_minutes_consumed']
            start_time = form.cleaned_data['start_time']

            models.SubAssignment.objects.create(assignment_id=assignment_id,
                                                pre_sub_assignment=pre_sub_assignment,
                                                user_id=user.id,
                                                description=description,
                                                weight=weight, deadline=deadline, expected_minutes_consumed=emc)
            models.Schedule.objects.create(user_id=user.id, description=description, type="学习", is_repeated=False,
                                           is_done=False, start_time=start_time, weight=weight, deadline=deadline,
                                           expected_minutes_consumed=emc)
            return HttpResponseRedirect(reverse('helper:group_home', args=(pk, )))
        else:
            message = "添加失败！"
            return render(request, "../templates/group/add_sub_assign.html", {'form': form, 'message': message})


@login_required
def add_assign(request, pk):
    user = request.user
    group = get_object_or_404(models.Group, pk=pk)
    if user.id != group.leader.id:
        return HttpResponseForbidden
    if request.method == "GET":
        form = AssignmentForm()
        return render(request, "../templates/group/add_assign.html", {'form': form})
    else:
        form = AssignmentForm(request.POST)
        if form.is_valid():
            models.GroupAssignment.objects.create(description=form.cleaned_data['description'],
                                                  deadline=form.cleaned_data['deadline'],
                                                  group_id=pk)
            return HttpResponseRedirect(reverse('helper:group_home', args=(pk, )))
        else:
            return render(request, "../templates/group/add_assign.html", {'message': "添加失败！", 'form': form})


@login_required
def home(request, pk):
    user = request.user
    group = get_object_or_404(models.Group, pk=pk)
    user_group = models.UserGroup.objects.filter(group=group)
    partcipants = list(map(lambda k: k.user.id, user_group))
    if not (user.id in partcipants):
        return HttpResponseForbidden
    assignments = models.GroupAssignment.objects.filter(group=group)
    sub_assignments = models.SubAssignment.objects.filter(assignment__group=group)
    return render(request, '../templates/group/home.html', {
        'group': group,
        'partcipants': user_group,
        'assignments': assignments,
        'sub_assignments': sub_assignments
    })


# @login_required
# def add(request):
#     if request.method == "GET":
#         form = GroupForm()
#         return render(request, "../templates/group/add.html", {'form': form})
#     else:
#         form = GroupForm(request.POST)
#         if form.is_valid():
#             user = request.user
#
#             group = models.Group(type=form.cleaned_data['type'],
#                                  group_name=form.cleaned_data['group_name'],
#                                  leader=user)
#             group.save()
#
#             models.UserGroup.objects.create(is_leader=True,
#                                             group=group,
#                                             user=user)
#
#             return render(request, '../templates/group/add.html', {'form': form})
#         else:
#             return render(request, '../templates/group/add.html', {'form': form, 'message': '表单无效！'})
#
#
# @login_required
# def join(request):
#     if request.method == "GET":
#         groups = models.Group.objects.all()
#         return render(request, "../templates/group/join.html", {'groups': groups})
#     if request.is_ajax():
#         user = request.user
#         group_id = request.POST.get('group_id')
#         status = {'status': None}
#
#         result = models.UserGroup.objects.filter(user=user, group_id=group_id)
#         if result.count() == 0:
#             models.UserGroup.objects.create(is_leader=False, group_id=group_id, user=user)
#             status['status'] = 200
#         else:
#             status['status'] = 400
#         return JsonResponse(status)

templates/group/add_assign.html
<!DOCTYPE html>
<html lang="en">

<head>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Adding Main Task</title>

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
{% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body class="bg-gradient-primary">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white  mb-4 static-top shadow-lg">
                    <a href="{% url 'helper:home' %}">CHD Wiki</a>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                <!-- Nav Item - User Information -->
                <li class="nav-item">
                    <a class="nav-link" id="userName">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userId">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userEmail">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:home' %}">
                        <span class="mr-2 d-none d-lg-inline text-primary small">返回主页</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="loginOut" role="button" href="#" onclick="window.close();">
                        <span class="mr-2 d-none d-lg-inline text-danger small">关闭页面</span>
                    </a>
                </li>
            </ul>
        </nav></div>

            <!-- Content Column -->
            <div class="col-xl-8 col-lg-12 col-md-12 m-auto">

                <!-- Assignment -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3 ">
                        <h6 class="m-0 font-weight-bold text-primary text-center">添加小组任务</h6>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                        <input type="submit" class="btn btn-primary btn-user btn-block" value="提交">
                        {% if message %}
                        <script>
                           mes="{{message}}";
                           if(!mes.match("message"))
                             alert(mes);
                        </script>
                        {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

</body>

templates/group/add_sub_assign.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Adding Sub Task</title>

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
{% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body class="bg-gradient-primary">

    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white  mb-4 static-top shadow-lg">
                    <a href="{% url 'helper:home' %}">CHD Wiki</a>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                <!-- Nav Item - User Information -->
                <li class="nav-item">
                    <a class="nav-link" id="userName">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userId">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="userEmail">
                        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:home' %}">
                        <span class="mr-2 d-none d-lg-inline text-primary small">返回主页</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="loginOut" role="button" href="#" onclick="window.close();">
                        <span class="mr-2 d-none d-lg-inline text-danger small">关闭页面</span>
                    </a>
                </li>
            </ul>
        </nav></div>

            <!-- Content Column -->
            <div class="col-xl-8 col-lg-12 col-md-12 m-auto">

                <!-- Blog -->
                <div class="card shadow mb-4">
                    <div class="card-header py-3 ">
                        <h6 class="m-0 font-weight-bold text-primary text-center">添加子任务</h6>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {{ form }}
                            <input type="submit" class="btn btn-primary btn-user btn-block" value="提交">
                            {% if message %}
                            <script>
                                mes = "{{message}}";
                                if (!mes.match("message"))
                                    alert(mes);
                            </script>
                            {% endif %}
                        </form>
                    </div>
                </div>
            </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

</body>

templates/group/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Group Home</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-icon">
                    <img src="../../static/img/logo.png" class="fas fa-laugh-wink" width="50" height="50"></img>
                </div>
                <div class="sidebar-brand-text mx-3">CHD Wiki</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                博客
            </div>

            <!-- Nav Item - My Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门博客</span>
                </a>
            </li>

            <!-- Nav Item -  Hot Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:blog_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的博客</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                小组
            </div>
            <!-- Nav Item - Group Task Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:group_admin' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>小组任务</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>CHD Wiki</strong> 助力每一个CHDer</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item">
                            <a class="nav-link" id="userName">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userId">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userEmail">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                            </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">{{ group.group_name }}</h1>
                        <p>组长：{{ group.leader.username }}</p>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-9 mb-4">

                            <!-- Main Task -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">小组任务</h6>
                                </div>
                                <div class="card-body">
                                    {% if request.user.id == group.leader.id %}
                                        <p><a target="_blank" href="{% url 'helper:assign_add' group.id %}">新建任务</a></p>
                                    {% endif %}
                                    <ul>
                                        {% if assignments %}
                                            {% for a in assignments %}
                                                <li>{{ a.description }} {{ a.deadline }}</li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>

                            <!-- Sub Task -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">小组子任务</h6>
                                </div>
                                <div class="card-body">
                                    {% if request.user.id == group.leader.id %}
                                        <p><a target="_blank" href="{% url 'helper:sub_assign_add' group.id %}">新建子任务</a></p>
                                    {% endif %}
                                    <ul>
                                        {% if sub_assignments %}
                                            {% for a in sub_assignments %}
                                                <li>{{ a.description }} {{ a.deadline }} {{ a.user.username }}</li>
                                            {% endfor %}
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>

                        </div>

                        <div class="col-lg-3 mb-4">

                            <!-- Friends List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">成员列表</h6>
                                </div>
                                <div class="card-body">
                                    {% if partcipants %}
                                        <ul>
                                        {% for p in partcipants %}
                                            <li><a target="_blank" href="{% url 'helper:public' p.user.id %}">
                                                {{ p.user.username }} {{ p.user.profile.name }}
                                            </a></li>
                                            {% if message %}
                                                <script>
                                                    mes="{{message}}";
                                                    if(!mes.match("message"))
                                                        alert(mes);
                                                </script>
                                            {% endif %}
                                        {% endfor %}
                                        </ul>
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>