CHD_Wiki/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('Wiki.urls')),
    path("admin/", admin.site.urls),
]

Wiki/urls.py
from django.urls import path
from .views import user, blog, schedule, group


app_name = 'helper'
urlpatterns = [
    path('register/', user.register, name='register'),
    path('login/', user.login, name='login'),
    path('zy/', user.zy, name='zy'),
    path('kc/', user.kc, name='kc'),
    path('gy/', user.gy, name='gy'),
    path('', user.index, name='index'),
    path('user/home/', user.home, name='home'),
    path('user/pwd_change/', user.pwd_change, name='pwd_change'),
    path('user/friends_admin/', user.friends_admin, name='friends_admin'),
    path('blog/home/', blog.home, name='blog_homepage'),
    path('blog/hot/<int:pg>', blog.hot, name='hot'),
    path('blog/<int:pk>/modify', blog.modify, name='blog_modify'),
    path('blog/<int:pk>/delete', blog.delete, name='blog_delete'),
    path('blog/add', blog.add, name='blog_add'),
    path('blog/<int:pk>/', blog.blog, name='blog_page'),
    path('blog/friend/<int:friend_id>/', blog.public, name='public'),
    path('logout/', user.logout, name='logout'),
    path('group/', group.group_admin, name='group_admin'),
    path('group/<int:pk>/', group.home, name='group_home'),
    path('group/<int:pk>/add_assign/', group.add_assign, name='assign_add'),
    path('group/<int:pk>/add_sub_assign/', group.add_sub_assign, name='sub_assign_add'),
    path('schedule/', schedule.home, name='schedule_home'),
    path('schedule/add/', schedule.add_todo_list, name='schedule_add'),
    path('schedule/daily', schedule.daily_schedules, name='schedule_daily'),
]

Wiki/views/user.py
from django import forms
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.db.models import Q
from ..models import *
from .settings import *
from .schedule import get_schedules
import datetime
import copy


class RegistrationForm(forms.Form):
    TYPE_CHOICES = [('S', '学生'), ('T', '教师')]
    GENDER_CHOICES = [('M', '男'), ('F', '女')]

    user_id = forms.CharField(label='学/工号', max_length=7,
                              widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    email = forms.EmailField(label='邮箱',
                             widget=forms.EmailInput(attrs={'class': 'form-control form-control-user mb-5'}))
    user_name = forms.CharField(label='昵称', max_length=10,
                                widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    gender = forms.ChoiceField(label='性别', widget=forms.RadioSelect, choices=GENDER_CHOICES)
    user_type = forms.ChoiceField(label='用户类型', widget=forms.RadioSelect, choices=TYPE_CHOICES)
    class_name = forms.CharField(label='班级', max_length=10, required=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control form-control-user mb-5'}))
    password1 = forms.CharField(label='密码',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))
    password2 = forms.CharField(label='再次输入密码',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))


class LoginForm(forms.Form):
    email = forms.EmailField(label='邮箱',
                             widget=forms.EmailInput(attrs={'class': 'form-control form-control-user mb-5'}))
    password = forms.CharField(label='密码',
                               widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))


class PwdChangeForm(forms.Form):
    old_password = forms.CharField(label='旧的密码',
                                   widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))

    password1 = forms.CharField(label='密码',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))
    password2 = forms.CharField(label='再次输入密码',
                                widget=forms.PasswordInput(attrs={'class': 'form-control form-control-user mb-5'}))


def register(request):
    message = None
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user_id = form.cleaned_data['user_id']
            user_name = form.cleaned_data['user_name']
            email = form.cleaned_data['email']
            gender = form.cleaned_data['gender']
            user_type = form.cleaned_data['user_type']
            class_name = form.cleaned_data['class_name']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if user_type == 'S' and len(user_id) != 7:
                message = "请输入有效的学号。"
            elif user_type == 'T' and len(user_id) != 6:
                message = "请输入有效的工号。"
            else:
                filter_result = User.objects.filter(username__exact=user_id)
                if len(filter_result) > 0:
                    message = "您的学/工号已被注册过。"

            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                message = "您的邮箱已被注册过。"

            if password1 and password2 and password1 != password2:
                message = '两次输入的密码不一致，请重新输入'

            if message is None:
                user = User.objects.create_user(username=user_id, password=password1, email=email)
                user_profile = Profile(class_name=class_name, type=user_type, gender=gender, user=user, name=user_name)
                user_profile.save()
                return HttpResponseRedirect(reverse("helper:login"))
    else:
        form = RegistrationForm()
    return render(request, '../templates/user/register.html', {'form': form, 'message': message})


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) == 0:
                message = "邮箱不存在。"
                return render(request, '../templates/user/login.html',
                              {'form': form, 'message': message})

            user = User.objects.filter(email__exact=email)
            user_id = user.get().username
            user = auth.authenticate(username=user_id, password=password)
            if user is not None and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('helper:home'))
            else:
                message = '密码错误，请重新输入！'
                return render(request, '../templates/user/login.html',
                              {'form': form, 'message': message})
    else:
        form = LoginForm()
    return render(request, '../templates/user/login.html', {'form': form})


def index(request):
    return render(request, "../templates/index.html")


def zy(request):
    return render(request, "../templates/services.html")


def contacts(request):
    return render(request, "../templates/contacts.html")


def gy(request):
    return render(request, "../templates/pricing.html")


def kc(request):
    return render(request, "../templates/projects.html")


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("helper:login"))


@login_required
def pwd_change(request):
    user = request.user

    if request.method == "POST":
        form = PwdChangeForm(request.POST)
        if form.is_valid():
            password = form.cleaned_data['old_password']
            username = user.username

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                password1 = form.cleaned_data['password1']
                password2 = form.cleaned_data['password2']
                if password1 and password2 and password1 != password2:
                    return render(request, '../templates/user/pwd_change.html',
                                  {'form': form, 'user': user, 'message': '两次输入的密码不一致，请重新输入！'})
                user.set_password(password2)
                user.save()
                return HttpResponseRedirect(reverse('helper:login'))

            else:
                return render(request, '../templates/user/pwd_change.html',
                              {'form': form, 'user': user, 'message': '旧密码错误！'})
    else:
        form = PwdChangeForm()

    return render(request, '../templates/user/pwd_change.html', {'form': form, 'user': user})


def get_aside(user):
    schedule_not_repeated = user.schedule_set.filter(is_done__exact=False, is_repeated__exact=False)
    schedule_daily = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='D',
                                              deadline__gte=timezone.now(), start_time__lte=timezone.now())
    schedule_weekly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='W',
                                               deadline__gte=timezone.now(), start_time__lte=timezone.now())
    schedule_monthly = user.schedule_set.filter(is_repeated__exact=True, repeat_cycle__exact='M',
                                                deadline__gte=timezone.now(), start_time__lte=timezone.now())

    def update_time(s):
        interval = time.date() - s.start_time.date()
        s.start_time += datetime.timedelta(days=interval.days)

    schedules = list(schedule_not_repeated)
    for i in range(HOMEPAGE_SCHEDULE_DAY):
        time = datetime.datetime.now() + datetime.timedelta(days=i)
        for j in range(len(schedule_daily)):
            s = copy.copy(schedule_daily[j])
            update_time(s)
            schedules.append(s)
        for j in range(len(schedule_weekly)):
            s = copy.copy(schedule_weekly[j])
            if s.start_time.weekday() == time.weekday():
                update_time(s)
                schedules.append(s)
        for j in range(len(schedule_monthly)):
            s = copy.copy(schedule_monthly[j])
            if s.start_time.day == time.day:
                update_time(s)
                schedules.append(s)
    schedules.sort(key=lambda sc: sc.start_time)

    group_sub_assignments = user.subassignment_set.all().order_by('deadline')

    friends = Friend.objects.filter(user_id__exact=user.id, authority__gte=1)
    return schedules, group_sub_assignments, friends


@login_required
def home(request):
    user = request.user

    schedules, group_sub_assignments, friends = get_aside(user)
    schedules = get_schedules(user, HOMEPAGE_SCHEDULE_DAY)

    blogs = Blog.objects.filter(Q(user__blog__pageview__gte=HOT_BLOG_PAGEVIEW,
                                  modified_time__gte
                                  =timezone.now() - datetime.timedelta(days=HOMEPAGE_HOT_BLOG_DAY)) |
                                Q(modified_time__gte
                                  =timezone.now() - datetime.timedelta(
                                    days=HOMEPAGE_COMMON_BLOG_DAY))).distinct().order_by('-pageview')
    if len(blogs) > HOMEPAGE_BLOG_NUMBER:
        blogs = blogs[:HOMEPAGE_BLOG_NUMBER]

    return render(request, '../templates/user/home.html',
                  {
                      'user': user,
                      'schedules': schedules,

templates/user/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Home Page</title>

    <!-- Custom fonts for this template-->
    {% load static %}
    <link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center " href="{% url 'helper:home' %}">
                <div class="sidebar-brand-icon">
                    <img src="../../static/img/logo.png" class="fas fa-laugh-wink" width="50" height="50"></img>
                </div>
                <div class="sidebar-brand-text mx-3">CHD Wiki</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'helper:home' %}">
                    <i class="fas fa-fw fa-sun"></i>
                    <span>我的主页</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                博客
            </div>

            <!-- Nav Item - My Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:hot' 1 %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>热门博客</span>
                </a>
            </li>

            <!-- Nav Item -  Hot Blog Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:blog_homepage' %}">
                    <i class="fas fa-fw fa-newspaper"></i>
                    <span>我的博客</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                好友
            </div>

            <!-- Nav Item - Friends Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:friends_admin' %}">
                    <i class="fas fa-fw fa-user-friends"></i>
                    <span>我的好友</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                日程
            </div>
            <!-- Nav Item - Schedule Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:schedule_home' %}">
                    <i class="fas fa-fw fa-calculator"></i>
                    <span>我的日程</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                小组
            </div>
            <!-- Nav Item - Group Task Menu -->
            <li class="nav-item">
                 <a class="nav-link" href="{% url 'helper:group_admin' %}">
                    <i class="fas fa-fw fa-tasks"></i>
                    <span>小组任务</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <p class="text-center mb-2"><strong>CHD Wiki</strong> 助力每一个想要学习编程的CHDer</p>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white mb-4 static-top shadow">

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - User Information -->
                        <li class="nav-item">
                            <a class="nav-link" id="userName">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.profile.name }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userId">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="userEmail">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                            </a>
                    </li>
                        <li class="nav-item">
                            <a class="nav-link" id="pwdChange" role="button" href="{% url 'helper:pwd_change' %}">
                                <span class="mr-2 d-none d-lg-inline text-primary small">更改密码</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="loginOut" role="button" href="{% url 'helper:logout' %}">
                                <span class="mr-2 d-none d-lg-inline text-danger small">退出登录</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">我的空间</h1>
                    </div>

                    <div class="row">

                        <!-- Content Column -->
                        <div class="col-lg-9 mb-4">

                            <!-- Hot Blogs -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 target="_blank" class="m-0 font-weight-bold text-primary">热门博客</h6>
                                </div>
                                <div class="card-body">
                                    <article>
                                            {% if blogs %}
                                                {% for b in blogs %}
                                                <h4><a target="_blank" href="{% url 'helper:blog_page' b.id %}">{{ b.title }}</a></h4>
                                                <p>{{ b.created_time }} 热度:{{ b.pageview }}</p>
                                                <p>{{ b.content|truncatechars:200 }}</p>
                                                    <hr class="divider">
                                                {% endfor %}
                                                {% endif %}
                                    </article>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-3 mb-4">

                            <!-- Friends List -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">好友列表</h6>
                                </div>
                                <div class="card-body">
                                    {% if friends %}
                                        <ul>
                                            {% for f in friends %}
                                            <li>
                                                <a target="_blank" href="{% url 'helper:public' f.friend.id %}">
                                                    {{ f.friend.username }} {{ f.friend.profile.name }}
                                                </a>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}
                                    <p><a target="_blank" rel="nofollow" href="{% url 'helper:friends_admin' %}">更多 &rarr;</a></p>
                                </div>
                            </div>

                            <!-- Schedule -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">个人日程</h6>
                                </div>
                                <div class="card-body">
                                    {% if schedules %}
                                        <ol>
                                            {% for s in schedules %}
                                                <li>{{ s.description }}    {{ s.start_time }}</li>
                                            {% endfor %}
                                        </ol>
                                    {% endif %}
                                    <p><a target="_blank" rel="nofollow" href="{% url 'helper:schedule_home' %}">更多 &rarr;</a></p>
                                </div>
                            </div>

                            <!-- Group Task -->
                            <div class="card shadow mb-4">
                                <div class="card-header py-3">
                                    <h6 class="m-0 font-weight-bold text-primary">小组任务</h6>
                                </div>
                                <div class="card-body">
                                    {% if group_sub_assignments %}
                                        <ol>
                                            {% for a in group_sub_assignments %}
                                                <li>{{ a.description }}    {{ a.deadline }}</li>
                                            {% endfor %}
                                        </ol>
                                    {% endif %}
                                    <p><a target="_blank" rel="nofollow" href="{% url 'helper:group_admin' %}">更多 &rarr;</a></p>
                                </div>
                            </div>

                        </div>
                    </div>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9 m-5">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">CHD Wiki</h1>
                                    </div>
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ form }}
                                        <input type="submit" class="btn btn-primary btn-user btn-block" value="登录">
                                        {% if message %}
                                        <script>
                                            mes = "{{message}}";
                                            if (!mes.match("message"))
                                                alert(mes);
                                        </script>
                                        {% endif %}
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'helper:register' %}">还没账户？创建一个!</a>
                                    </div>
                                    <div class="text-center">
                                        <p class="small">Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

</body>

</html>

templates/user/pwd_change.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Password Changing</title>

    <!-- Custom fonts for this template-->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/Study_Helper.css' %}">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9 m-5">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-register-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">修改密码</h1>
                                    </div>
                                    <form method="post">
                                        {% csrf_token %}
                                        {{ form }}
                                        <input type="submit" class="btn btn-primary btn-user btn-block" value="修改">
                                        {% if message %}
                                        <script>
                                            mes = "{{message}}";
                                            if (!mes.match("message"))
                                                alert(mes);
                                        </script>
                                        {% endif %}
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <p class="small">Copyright © 刘易行
            李欢欢 2023届中国大学生计算机设计大赛</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/Study_Helper.js' %}"></script>

</body>

</html>